export const metaAdapter={
  provider:'meta',status:'active',requirements:['META_APP_ID','META_APP_SECRET'],
  capabilities:{receiveMessages:true,sendMessages:true,comments:true,oauth:true,webhook:true},
  async sendText({token,recipientId,text,accountId,graphVersion='v21.0',fetchImpl}){const response=await fetchImpl(`https://graph.facebook.com/${graphVersion}/${accountId}/messages?access_token=${encodeURIComponent(token)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({recipient:{id:recipientId},messaging_type:'RESPONSE',message:{text}})});const body=await response.json();if(!response.ok||body.error)throw metaSendError(body.error);return {externalMessageId:String(body.message_id||''),sentAt:Date.now(),raw:body}},
  async sendImage({token,recipientId,imageUrl,data,mimeType='image/jpeg',filename='image.jpg',accountId,graphVersion='v21.0',fetchImpl}){const endpoint=`https://graph.facebook.com/${graphVersion}/${accountId}/messages?access_token=${encodeURIComponent(token)}`;let response;if(data){const form=new FormData();form.set('recipient',JSON.stringify({id:recipientId}));form.set('messaging_type','RESPONSE');form.set('message',JSON.stringify({attachment:{type:'image',payload:{is_reusable:false}}}));form.set('filedata',new Blob([data],{type:mimeType}),filename);response=await fetchImpl(endpoint,{method:'POST',body:form})}else{response=await fetchImpl(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({recipient:{id:recipientId},messaging_type:'RESPONSE',message:{attachment:{type:'image',payload:{url:imageUrl,is_reusable:false}}}})})}const body=await response.json();if(!response.ok||body.error)throw metaSendError(body.error);return {externalMessageId:String(body.message_id||''),sentAt:Date.now(),raw:body}},
  normalizeEntry(entry){const events=[];for(const item of entry.messaging||[]){if(!item.message?.mid)continue;const outgoing=Boolean(item.message.is_echo),peerId=String((outgoing?item.recipient?.id:item.sender?.id)||'');events.push({type:'message',externalEventId:String(item.message.mid),conversationId:peerId,senderId:peerId,senderName:'',direction:outgoing?'outgoing':'incoming',text:String(item.message.text||''),messageId:String(item.message.mid),timestamp:Number(item.timestamp||entry.time||Date.now()),attachments:item.message.attachments||[],raw:item})}return events}
}

function metaSendError(value){const detail=String(value?.message||'Meta Send API từ chối yêu cầu'),outsideWindow=/24|window|allowed|response time/i.test(detail),error=new Error(outsideWindow?'Facebook chỉ cho Page trả lời trong vòng 24 giờ kể từ tin nhắn gần nhất của khách. Hãy chờ khách nhắn lại rồi gửi tiếp.':`Facebook từ chối gửi tin: ${detail}`);error.expose=true;return error}
