import { useEffect, useMemo, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { AtSign, BarChart3, Bot, Boxes, ChevronDown, CircleHelp, ClipboardList, ContactRound, GraduationCap, Inbox, LayoutDashboard, MessageCircle, MessagesSquare, MoreHorizontal, Package, Plus, Search, Send, Settings, ShieldCheck, Sparkles, Store, Tag, Users, Wifi, X } from 'lucide-react'
import { db, seedDatabase, type Channel, type Conversation, type Message } from './db'

type Page = 'dashboard'|'inbox'|'customers'|'orders'|'products'|'ai'|'team'|'reports'|'connections'|'settings'
const nav: Array<[Page,string,any]> = [
  ['dashboard','Tổng quan',LayoutDashboard], ['inbox','Hộp thư',Inbox], ['customers','Khách hàng',ContactRound],
  ['orders','Đơn hàng',ClipboardList], ['products','Sản phẩm',Package], ['ai','Huấn luyện AI',GraduationCap],
  ['team','Nhân viên',Users], ['reports','Báo cáo',BarChart3], ['connections','Kết nối kênh',Wifi], ['settings','Cài đặt',Settings]
]
const channelIcon = (c:Channel) => c==='facebook'?<MessagesSquare/>:c==='instagram'?<AtSign/>:c==='telegram'?<Send/>:<MessageCircle/>
const channelName:Record<Channel,string> = {facebook:'Facebook',instagram:'Instagram',zalo:'Zalo OA',telegram:'Telegram',tiktok:'TikTok'}

function App(){
  const [page,setPage]=useState<Page>('inbox'); const [selected,setSelected]=useState('v1'); const [draft,setDraft]=useState(''); const [aiOpen,setAiOpen]=useState(true)
  useEffect(()=>{seedDatabase()},[])
  return <div className="app-shell"><Sidebar page={page} setPage={setPage}/><main><Topbar page={page}/>{page==='inbox'?<InboxPage selected={selected} setSelected={setSelected} draft={draft} setDraft={setDraft} aiOpen={aiOpen} setAiOpen={setAiOpen}/>:<ModulePage page={page}/>}</main></div>
}

function Sidebar({page,setPage}:{page:Page,setPage:(p:Page)=>void}){
 return <aside className="sidebar"><div className="brand"><div className="brand-mark"><Bot/></div><div><b>BOT 68</b><small>Omnichannel AI</small></div></div><button className="workspace"><span className="store-logo"><Store/></span><span><small>Cửa hàng</small><b>BOT 68 Demo</b></span><ChevronDown/></button><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/><span>{label}</span>{id==='inbox'&&<em>3</em>}</button>)}</nav><div className="sidebar-foot"><div className="plan"><Sparkles/><div><b>Gói thử nghiệm</b><small>Còn 30 ngày</small></div></div><button><CircleHelp/><span>Trợ giúp</span></button></div></aside>
}
function Topbar({page}:{page:Page}){const title=nav.find(n=>n[0]===page)?.[1];return <header className="topbar"><div><h1>{title}</h1><p>{page==='inbox'?'Quản lý tất cả cuộc trò chuyện tại một nơi':'Trung tâm quản lý BOT 68'}</p></div><div className="top-actions"><button className="connection"><i/>Máy chủ thử nghiệm</button><button className="avatar">68</button></div></header>}

function InboxPage({selected,setSelected,draft,setDraft,aiOpen,setAiOpen}:{selected:string;setSelected:(s:string)=>void;draft:string;setDraft:(s:string)=>void;aiOpen:boolean;setAiOpen:(b:boolean)=>void}){
 const conversations=useLiveQuery(()=>db.conversations.orderBy('updatedAt').reverse().toArray())||[]; const contacts=useLiveQuery(()=>db.contacts.toArray())||[]
 const active=conversations.find(c=>c.id===selected)||conversations[0]; const contact=contacts.find(c=>c.id===active?.contactId)
 return <div className="inbox-grid"><section className="thread-list"><div className="filters"><div className="search"><Search/><input placeholder="Tìm tên, số điện thoại..."/></div><button><MoreHorizontal/></button></div><div className="tabs"><button className="active">Tất cả <b>{conversations.length}</b></button><button>Chưa đọc <b>3</b></button><button>Đang mở</button></div><div className="channel-chips"><button className="active">Tất cả</button>{(['facebook','instagram','zalo','telegram'] as Channel[]).map(c=><button title={channelName[c]} key={c}>{channelIcon(c)}</button>)}</div><div className="threads">{conversations.map(c=><ThreadItem key={c.id} item={c} contact={contacts.find(x=>x.id===c.contactId)} active={c.id===active?.id} onClick={()=>setSelected(c.id)}/>)}</div></section>{active&&contact&&<Chat active={active} contact={contact} draft={draft} setDraft={setDraft} aiOpen={aiOpen} setAiOpen={setAiOpen}/>} {contact&&<CustomerPanel contact={contact}/>}</div>
}
function ThreadItem({item,contact,active,onClick}:any){return <button className={'thread '+(active?'active':'')} onClick={onClick}><span className="contact-avatar">{contact?.avatar}<i className={item.channel}/></span><span className="thread-copy"><span><b>{contact?.name}</b><time>{item.updatedAt>Date.now()-600000?'Vừa xong':'Hôm nay'}</time></span><p>{item.preview}</p><small>{item.assignee}</small></span>{item.unread>0&&<em>{item.unread}</em>}</button>}
function Chat({active,contact,draft,setDraft,aiOpen,setAiOpen}:any){const messages=useLiveQuery(()=>db.messages.where('conversationId').equals(active.id).sortBy('createdAt'),[active.id])||[];async function send(from:'agent'|'ai'='agent'){if(!draft.trim())return;await db.messages.add({id:crypto.randomUUID(),conversationId:active.id,from,text:draft.trim(),createdAt:Date.now()});await db.conversations.update(active.id,{preview:draft.trim(),updatedAt:Date.now()});setDraft('')}
 return <section className="chat"><div className="chat-head"><div className="contact-avatar large">{contact.avatar}<i className={active.channel}/></div><div><b>{contact.name}</b><small><span className="online"/> {channelName[active.channel as Channel]} · Đang hoạt động</small></div><div className="chat-actions"><button title="Gắn nhãn"><Tag/></button><button title="Tạo đơn"><Boxes/></button><button><MoreHorizontal/></button></div></div><div className="messages"><div className="day">Hôm nay</div>{messages.length?messages.map((m:Message)=><div key={m.id} className={'bubble-row '+m.from}><div className="bubble">{m.from==='ai'&&<small><Bot/> AI BOT 68</small>}{m.text}<time>{new Date(m.createdAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</time></div></div>):<div className="empty-chat"><MessageCircle/><b>Bắt đầu cuộc trò chuyện</b></div>}</div>{aiOpen&&<div className="ai-suggest"><span><Sparkles/></span><div><b>AI đề xuất</b><p>Chào Minh Anh, mẫu màu đen size M hiện vẫn còn hàng. Bạn muốn shop giữ hàng và tạo đơn luôn không ạ?</p><button onClick={()=>setDraft('Chào Minh Anh, mẫu màu đen size M hiện vẫn còn hàng. Bạn muốn shop giữ hàng và tạo đơn luôn không ạ?')}>Dùng câu trả lời</button></div><button className="close" onClick={()=>setAiOpen(false)}><X/></button></div>}<div className="composer"><div className="quick"><button><Plus/></button><button onClick={()=>setAiOpen(true)}><Sparkles/> AI gợi ý</button><button>Mẫu trả lời</button></div><div className="compose-box"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Nhập tin nhắn..."/><button className="send" onClick={()=>send()}><Send/></button></div><small>Enter để gửi · Shift + Enter để xuống dòng</small></div></section>}
function CustomerPanel({contact}:any){return <aside className="customer-panel"><div className="profile"><div className="profile-avatar">{contact.avatar}</div><h3>{contact.name}</h3><p>{contact.phone||'Chưa có số điện thoại'}</p><span className="source"><MessagesSquare/> Khách hàng Facebook</span></div><div className="panel-section"><div className="section-title"><b>Thông tin khách hàng</b><button>Chỉnh sửa</button></div><dl><dt>Số điện thoại</dt><dd>{contact.phone||'Chưa cập nhật'}</dd><dt>Địa chỉ</dt><dd>Chưa cập nhật</dd><dt>Người phụ trách</dt><dd>Nguyễn Thành</dd></dl></div><div className="panel-section"><div className="section-title"><b>Nhãn khách hàng</b><button><Plus/></button></div><div className="tags">{contact.tags.map((t:string)=><span key={t}>{t}</span>)}</div></div><div className="panel-section"><div className="section-title"><b>Đơn hàng gần đây</b><button>Xem tất cả</button></div><div className="empty-order"><ClipboardList/><p>Chưa có đơn hàng</p><button><Plus/> Tạo đơn mới</button></div></div></aside>}

const moduleCopy:Record<Exclude<Page,'inbox'>,{icon:any,title:string,desc:string,stats?:string[]}>= {
 dashboard:{icon:LayoutDashboard,title:'Tổng quan hoạt động',desc:'Theo dõi tin nhắn, khách hàng, đơn hàng và hiệu suất nhân viên.',stats:['148 hội thoại','36 khách mới','12 đơn hàng','92% phản hồi']},
 customers:{icon:ContactRound,title:'Quản lý khách hàng',desc:'Hồ sơ hợp nhất, nhãn, ghi chú và toàn bộ lịch sử tương tác.',stats:['1.248 khách hàng','86 khách mới','214 khách quay lại']},
 orders:{icon:ClipboardList,title:'Quản lý đơn hàng',desc:'Tạo đơn ngay trong hội thoại và theo dõi quá trình giao hàng.',stats:['12 đơn mới','8 đang giao','126 hoàn thành']},
 products:{icon:Package,title:'Sản phẩm và tồn kho',desc:'Quản lý sản phẩm, biến thể, giá bán và số lượng tồn kho.'},
 ai:{icon:GraduationCap,title:'Trung tâm huấn luyện AI',desc:'Dạy AI phong cách tư vấn, kiến thức sản phẩm và các quy tắc an toàn.',stats:['24 tài liệu','86 câu hỏi mẫu','Chế độ: Gợi ý']},
 team:{icon:Users,title:'Nhân viên và phân quyền',desc:'Mời nhân viên, chia hội thoại và quản lý quyền truy cập.'},
 reports:{icon:BarChart3,title:'Báo cáo kinh doanh',desc:'Đo tốc độ phản hồi, hiệu suất tư vấn và tỷ lệ chốt đơn.'},
 connections:{icon:Wifi,title:'Kết nối các kênh',desc:'Kết nối tài khoản mạng xã hội bằng API chính thức.'},
 settings:{icon:Settings,title:'Cài đặt hệ thống',desc:'Dữ liệu cục bộ, sao lưu, bảo mật và thông tin cửa hàng.'}
}
function ModulePage({page}:{page:Exclude<Page,'inbox'>}){const m=moduleCopy[page];const Icon=m.icon;return <div className="module-page"><div className="module-hero"><div className="hero-icon"><Icon/></div><div><h2>{m.title}</h2><p>{m.desc}</p></div><button className="primary"><Plus/> Thêm mới</button></div>{m.stats&&<div className="stats">{m.stats.map((s,i)=><div key={s}><small>{['Tổng số','Trong tháng','Đang xử lý','Hiệu quả'][i]}</small><b>{s}</b><span>↗ Dữ liệu thử nghiệm</span></div>)}</div>}{page==='connections'?<Connections/>:page==='ai'?<AITraining/>:<div className="module-card"><div className="card-head"><b>Dữ liệu gần đây</b><div className="search compact"><Search/><input placeholder="Tìm kiếm..."/></div></div><div className="placeholder-table">{[1,2,3,4,5].map(n=><div key={n}><span className="skeleton circle"/><span className="skeleton wide"/><span className="skeleton"/><span className="skeleton short"/></div>)}</div></div>}</div>}
function Connections(){const channels:[Channel,string,string][]=[['facebook','Facebook Page','Tin nhắn và bình luận Fanpage'],['instagram','Instagram Professional','Tin nhắn và tương tác Instagram'],['zalo','Zalo Official Account','Chăm sóc khách hàng qua Zalo OA'],['telegram','Telegram Bot','Tin nhắn từ Telegram Bot'],['tiktok','TikTok Business','Phụ thuộc quyền API TikTok']];return <div className="connections">{channels.map(([id,name,desc],i)=><div className="connection-card" key={id}><span className={'channel-logo '+id}>{channelIcon(id)}</span><div><b>{name}</b><p>{desc}</p><small>{i<2?'Sẵn sàng cấu hình':'Sẽ triển khai ở giai đoạn tiếp theo'}</small></div><button onClick={()=>alert('Cần App ID và máy chủ HTTPS để kết nối thật.')}>{i<2?'Kết nối':'Tìm hiểu'}</button></div>)}</div>}
function AITraining(){return <div className="ai-grid"><div className="module-card"><div className="card-head"><b>Bộ kiến thức cửa hàng</b><button className="primary small"><Plus/> Thêm tài liệu</button></div>{['Thông tin và giờ mở cửa','Danh mục sản phẩm','Chính sách đổi trả','Kịch bản tư vấn'].map((x,i)=><div className="knowledge" key={x}><span><ClipboardList/></span><div><b>{x}</b><p>{[12,48,8,18][i]} mục đã huấn luyện</p></div><em>Hoạt động</em></div>)}</div><div className="module-card ai-policy"><ShieldCheck/><h3>Chế độ an toàn</h3><p>AI chỉ đề xuất câu trả lời. Nhân viên phải kiểm tra trước khi gửi cho khách.</p><label><input type="checkbox" defaultChecked/> Không tự báo giá khi thiếu dữ liệu</label><label><input type="checkbox" defaultChecked/> Chuyển khiếu nại cho nhân viên</label><label><input type="checkbox" defaultChecked/> Không yêu cầu thông tin nhạy cảm</label></div></div>}
export default App
