import { useState } from 'react'
import { Bot, Eye, EyeOff, LoaderCircle, LockKeyhole, ShieldCheck, Store } from 'lucide-react'
import { apiRequest, saveSession, type ServerSession } from './api'
export default function AuthScreen({onAuthenticated}:{onAuthenticated:(session:ServerSession)=>void}){
 const [mode,setMode]=useState<'login'|'register'>('login'),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const serverUrl='https://api.sportxauth.com',[businessName,setBusinessName]=useState('Cửa hàng của tôi'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('')
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{
  const body=mode==='register'?{businessName,name,email,password}:{email,password};const response=await apiRequest<Omit<ServerSession,'serverUrl'>>(serverUrl,`/api/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});const full={...response,serverUrl};await saveSession(full);onAuthenticated(full)
 }catch(err){setError(err instanceof Error?err.message:'Không thể tạo tài khoản')}finally{setBusy(false)}}
 return <div className="auth-page"><div className="auth-aside"><div className="auth-brand"><span><Bot/></span><b>BOT 68</b></div><div className="auth-pitch"><em>CHĂM SÓC KHÁCH HÀNG ĐA KÊNH</em><h1>Một hộp thư.<br/>Mọi khách hàng.<br/><strong>AI của riêng bạn.</strong></h1><p>Facebook, Instagram, Zalo, Telegram và TikTok trong một ứng dụng Windows bảo mật.</p><div className="auth-points"><span><ShieldCheck/> Dữ liệu hội thoại lưu tại máy</span><span><Store/> Mỗi cửa hàng có không gian riêng</span><span><LockKeyhole/> Tài khoản xác thực qua máy chủ BOT 68</span></div></div></div><div className="auth-main"><form onSubmit={submit} className="auth-card"><div className="auth-icon"><Bot/></div><h2>{mode==='login'?'Đăng nhập BOT 68':'Tạo tài khoản BOT 68'}</h2><p>{mode==='login'?'Đăng nhập tài khoản cửa hàng của bạn':'Tạo tài khoản chủ cửa hàng đầu tiên'}</p>{mode==='register'&&<><label><span>Tên cửa hàng</span><input value={businessName} onChange={e=>setBusinessName(e.target.value)} required/></label><label><span>Họ tên của bạn</span><input value={name} onChange={e=>setName(e.target.value)} required/></label></>}<label><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="ban@example.com" required/></label><label><span>Mật khẩu</span><div className="password"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<LockKeyhole/>}{mode==='login'?'Đăng nhập an toàn':'Tạo tài khoản'}</button><button type="button" className="auth-switch" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Chưa có tài khoản? Đăng ký':'Đã có tài khoản? Đăng nhập'}</button><small>Tài khoản được xác thực an toàn qua api.sportxauth.com.</small></form></div></div>
}
