import { useEffect, useState } from 'react'
import { Bot, Eye, EyeOff, LoaderCircle, LockKeyhole, Server, ShieldCheck, Store } from 'lucide-react'
import { apiRequest, saveSession, type ServerSession } from './api'
export default function AuthScreen({onAuthenticated}:{onAuthenticated:(session:ServerSession)=>void}){
 const [mode,setMode]=useState<'login'|'register'>('login'),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const [serverUrl,setServerUrl]=useState('http://127.0.0.1:6868'),[businessName,setBusinessName]=useState('BOT 68 Demo'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('')
 useEffect(()=>{window.bot68?.appInfo().then(info=>{if(info.localServerUrl)setServerUrl(info.localServerUrl);else if(info.localServerError)setError(`Máy chủ cục bộ: ${info.localServerError}`)}).catch(()=>{})},[])
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const body=mode==='register'?{businessName,name,email,password}:{email,password};const response=await apiRequest<Omit<ServerSession,'serverUrl'>>(serverUrl,`/api/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});const full={...response,serverUrl};await saveSession(full);onAuthenticated(full)}catch(err){setError(err instanceof Error?err.message:'Không thể kết nối máy chủ')}finally{setBusy(false)}}
 async function offline(){const session:ServerSession={serverUrl:'',token:'',offline:true,user:{id:'offline',tenantId:'offline',name:'Người dùng thử',email:'',role:'owner'},tenant:{id:'offline',name:'BOT 68 ngoại tuyến',slug:'offline',plan:'local'}};await saveSession(session);onAuthenticated(session)}
 return <div className="auth-page"><div className="auth-aside"><div className="auth-brand"><span><Bot/></span><b>BOT 68</b></div><div className="auth-pitch"><em>CHĂM SÓC KHÁCH HÀNG ĐA KÊNH</em><h1>Một hộp thư.<br/>Mọi khách hàng.<br/><strong>AI của riêng bạn.</strong></h1><p>Facebook, Instagram, Zalo, Telegram và TikTok trong một ứng dụng Windows bảo mật.</p><div className="auth-points"><span><ShieldCheck/> Dữ liệu hội thoại lưu tại máy</span><span><Store/> Mỗi cửa hàng có không gian riêng</span><span><LockKeyhole/> Phiên đăng nhập mã hóa bởi Windows</span></div></div></div><div className="auth-main"><form onSubmit={submit} className="auth-card"><div className="auth-icon"><Bot/></div><h2>{mode==='login'?'Đăng nhập BOT 68':'Tạo cửa hàng thử nghiệm'}</h2><p>{mode==='login'?'Tiếp tục quản lý hội thoại và khách hàng':'Tạo tài khoản chủ cửa hàng đầu tiên'}</p><label><span><Server/> Địa chỉ máy chủ</span><input value={serverUrl} onChange={e=>setServerUrl(e.target.value)} required/></label>{mode==='register'&&<><label><span>Tên cửa hàng</span><input value={businessName} onChange={e=>setBusinessName(e.target.value)} required/></label><label><span>Họ tên của bạn</span><input value={name} onChange={e=>setName(e.target.value)} required/></label></>}<label><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="ban@example.com" required/></label><label><span>Mật khẩu</span><div className="password"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<LockKeyhole/>}{mode==='login'?'Đăng nhập an toàn':'Tạo cửa hàng'}</button><button type="button" className="auth-switch" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Chưa có tài khoản? Tạo cửa hàng':'Đã có tài khoản? Đăng nhập'}</button><div className="auth-divider"><span>hoặc</span></div><button type="button" className="offline-button" onClick={offline}>Dùng thử ngoại tuyến trên máy này</button><small>Chế độ ngoại tuyến không nhận tin nhắn khi ứng dụng tắt.</small></form></div></div>
}
