import { useEffect, useState } from 'react'
import { ArchiveRestore, Database, Download, FolderLock, HardDrive, KeyRound, LoaderCircle, ShieldCheck, Upload } from 'lucide-react'
import { apiRequest, type ServerSession } from './api'
import { db, type Contact, type Conversation, type Message, type Order, type SyncEvent } from './db'
import './settings.css'

type LocalBackup={contacts:Contact[];conversations:Conversation[];messages:Message[];orders:Order[];syncEvents:SyncEvent[]}
type BackupPackage={format:'bot68-desktop-backup';version:1;createdAt:number;appVersion:string;tenant:{id:string;name:string};server:unknown|null;local:LocalBackup}

export default function SettingsPage({session}:{session:ServerSession}){
  const [info,setInfo]=useState({version:'',dataPath:'',localServerUrl:''}),[passphrase,setPassphrase]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  useEffect(()=>{window.bot68?.appInfo().then(setInfo).catch(()=>{})},[])
  async function exportBackup(){if(!window.bot68){setNotice('Sao lưu mã hóa chỉ khả dụng trong ứng dụng Windows.');return}if(passphrase.length<8){setNotice('Mật khẩu sao lưu phải có ít nhất 8 ký tự.');return}setBusy(true);setNotice('Đang thu thập và mã hóa dữ liệu...');try{const tenantId=session.tenant.id,[contacts,conversations,messages,orders,syncEvents,server]=await Promise.all([db.contacts.where('tenantId').equals(tenantId).toArray(),db.conversations.where('tenantId').equals(tenantId).toArray(),db.messages.where('tenantId').equals(tenantId).toArray(),db.orders.where('tenantId').equals(tenantId).toArray(),db.syncEvents.where('tenantId').equals(tenantId).toArray(),session.offline?Promise.resolve(null):apiRequest(session.serverUrl,'/api/backup/export',{},session.token)]);const value:BackupPackage={format:'bot68-desktop-backup',version:1,createdAt:Date.now(),appVersion:info.version,tenant:{id:tenantId,name:session.tenant.name},server,local:{contacts,conversations,messages,orders,syncEvents}};const saved=await window.bot68.saveBackup(value,passphrase);setNotice(saved.canceled?'Đã hủy sao lưu.':`Đã lưu bản sao mã hóa tại ${saved.filePath}`)}catch(e){setNotice(e instanceof Error?e.message:'Không thể sao lưu')}finally{setBusy(false)}}
  async function restoreBackup(){if(!window.bot68){setNotice('Khôi phục chỉ khả dụng trong ứng dụng Windows.');return}if(passphrase.length<8||confirm!=='KHOI PHUC'){setNotice('Nhập mật khẩu và gõ KHOI PHUC để xác nhận thay thế dữ liệu.');return}setBusy(true);setNotice('Đang mở và kiểm tra bản sao...');try{const opened=await window.bot68.openBackup(passphrase);if(opened.canceled)return setNotice('Đã hủy khôi phục.');const value=opened.value as BackupPackage;if(value?.format!=='bot68-desktop-backup'||value?.version!==1||!value.local)throw new Error('Gói sao lưu desktop không hợp lệ');for(const key of ['contacts','conversations','messages','orders','syncEvents'] as const)if(!Array.isArray(value.local[key]))throw new Error(`Dữ liệu ${key} không hợp lệ`);if(value.server&&!session.offline)await apiRequest(session.serverUrl,'/api/backup/import',{method:'POST',body:JSON.stringify({confirmation:'RESTORE',backup:value.server})},session.token);const tenantId=session.tenant.id,scope=<T extends {tenantId:string},>(items:T[])=>items.map(item=>({...item,tenantId}));await db.transaction('rw',db.contacts,db.conversations,db.messages,db.orders,db.syncEvents,async()=>{await db.messages.where('tenantId').equals(tenantId).delete();await db.conversations.where('tenantId').equals(tenantId).delete();await db.contacts.where('tenantId').equals(tenantId).delete();await db.orders.where('tenantId').equals(tenantId).delete();await db.syncEvents.where('tenantId').equals(tenantId).delete();await db.contacts.bulkPut(scope(value.local.contacts));await db.conversations.bulkPut(scope(value.local.conversations));await db.messages.bulkPut(scope(value.local.messages));await db.orders.bulkPut(scope(value.local.orders));await db.syncEvents.bulkPut(scope(value.local.syncEvents))});setNotice('Khôi phục thành công. Các kênh mạng xã hội cần kết nối lại để bảo vệ token. Ứng dụng sẽ tải lại.');setTimeout(()=>location.reload(),1800)}catch(e){setNotice(e instanceof Error?e.message:'Không thể khôi phục. Hãy kiểm tra mật khẩu sao lưu.')}finally{setBusy(false)}}
  return <div className="settings-grid"><section className="settings-card system-info"><div className="settings-title"><HardDrive/><div><h3>Dữ liệu trên máy này</h3><p>Máy chủ nhúng và cơ sở dữ liệu cục bộ</p></div></div><dl><dt>Phiên bản</dt><dd>BOT 68 {info.version||'—'}</dd><dt>Máy chủ</dt><dd>{info.localServerUrl||session.serverUrl||'Ngoại tuyến'}</dd><dt>Thư mục dữ liệu</dt><dd title={info.dataPath}>{info.dataPath||'Trình duyệt phát triển'}</dd><dt>Cơ sở dữ liệu</dt><dd>SQLite + IndexedDB</dd></dl><div className="security-note"><ShieldCheck/><span>Phiên đăng nhập và khóa máy chủ được Windows Safe Storage bảo vệ.</span></div></section><section className="settings-card backup-card"><div className="settings-title"><FolderLock/><div><h3>Sao lưu mã hóa</h3><p>Có thể chuyển sang máy Windows khác bằng mật khẩu riêng</p></div></div><label>Mật khẩu bản sao<div className="passphrase"><KeyRound/><input type="password" value={passphrase} onChange={e=>setPassphrase(e.target.value)} placeholder="Tối thiểu 8 ký tự"/></div></label><div className="backup-actions"><button className="primary" disabled={busy||session.user.role!=='owner'} onClick={exportBackup}>{busy?<LoaderCircle className="spin"/>:<Download/>} Tạo bản sao</button></div><small>Không xuất mật khẩu tài khoản hoặc token Facebook, Instagram, Zalo, Telegram. Sau khi chuyển máy, hãy kết nối lại các kênh.</small></section><section className="settings-card restore-card"><div className="settings-title"><ArchiveRestore/><div><h3>Khôi phục dữ liệu</h3><p>Thay thế dữ liệu kinh doanh và hộp thư hiện tại</p></div></div><label>Xác nhận<input value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Gõ KHOI PHUC"/></label><button className="restore-button" disabled={busy||session.user.role!=='owner'} onClick={restoreBackup}><Upload/> Chọn tệp và khôi phục</button><small>Thao tác này thay thế CRM, sản phẩm, đơn hàng, kiến thức AI và dữ liệu hội thoại trên máy. Tài khoản đăng nhập hiện tại được giữ lại.</small></section><section className="settings-card backup-details"><Database/><div><h3>Nội dung bản sao</h3><ul><li>Khách hàng, sản phẩm, tồn kho và đơn hàng</li><li>Hồ sơ AI và kho kiến thức từng cửa hàng</li><li>Hội thoại, tin nhắn và hàng đợi đồng bộ cục bộ</li><li>Mã hóa AES-256-GCM, khóa dẫn xuất bằng scrypt</li></ul></div></section>{notice&&<div className="settings-notice">{notice}</div>}</div>
}
